[build]
  publish = "."
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[functions]
  directory = ".netlify/functions"
