#!/usr/bin/env python3
"""
API handler for wallet scanning functionality
"""
import sys
import os
import json
import time
from pathlib import Path

# Add the project root to Python path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

# Import the wallet security agent
agent_available = False
try:
    from wallet_security_agent import WalletSecurityAgent
    from wallet_visualizer import WalletVisualizer
    agent_available = True
    print("Successfully imported wallet security agent and visualizer")
except Exception as e:
    print(f"Warning: Could not import wallet security agent: {e}")
    import traceback
    traceback.print_exc()
    agent_available = False

# Global storage for scan results (in production, use a proper database)
scan_results = {}
scan_status = {}

# Mock data for testing when agent is not available
def get_mock_scan_result(address):
    return f"""
🔍 WALLET SECURITY SCAN REPORT
================================

📋 WALLET ADDRESS: {address}

⚡ RISK ASSESSMENT:
Risk Score: 15/100
Risk Level: 🟡 LOW RISK

📊 SCAN SUMMARY:
• Total Transactions: 5
• Suspicious Activity: None detected
• Contract Interactions: 2
• Token Holdings: 3 different tokens

🚨 SECURITY FINDINGS:
• No immediate security threats detected
• Wallet appears to be used for legitimate transactions
• No interactions with known malicious contracts

💡 RECOMMENDATIONS:
• Continue monitoring wallet activity regularly
• Enable two-factor authentication if not already enabled
• Consider using a hardware wallet for additional security
• Keep software wallets updated to latest versions
• Be cautious of unsolicited token transfers

🔒 SECURITY STATUS: SAFE
================================
Report generated by Sentient Wallet Security AI Agent
Powered by @jackyjoeeth
"""

def handler(event, context):
    """Handle API requests"""
    try:
        print(f"API handler called with event: {event}")
        path = event.get('path', '')
        method = event.get('httpMethod', 'GET')
        print(f"Path: {path}, Method: {method}")
        
        # Handle CORS
        headers = {
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type'
        }
        
        # Handle preflight requests
        if method == 'OPTIONS':
            return {
                'statusCode': 200,
                'headers': headers,
                'body': ''
            }
        
        # Parse body for POST requests and query parameters for GET requests
        body = {}
        if method == 'POST' and event.get('body'):
            try:
                body = json.loads(event.get('body', '{}'))
            except:
                body = {}
        elif method == 'GET' and event.get('queryStringParameters'):
            body = event.get('queryStringParameters', {})
        
        # Route requests based on path
        print(f"Routing request: path={path}, method={method}")
        
        if path.endswith('/scan') and method == 'POST':
            print("Handling scan request")
            return handle_scan(body, headers)
        elif path.endswith('/status') and method == 'GET':
            print("Handling status request")
            return handle_status(body, headers)
        elif path.endswith('/health') and method == 'GET':
            print("Handling health request")
            return handle_health(headers)
        elif path.endswith('/test') and method == 'GET':
            print("Handling test request")
            return handle_test(headers)
        elif path.endswith('/debug') and method == 'GET':
            print("Handling debug request")
            return handle_debug(headers)
        else:
            print(f"Endpoint not found: {path}")
            return {
                'statusCode': 404,
                'headers': headers,
                'body': json.dumps({'error': 'Endpoint not found', 'path': path, 'method': method})
            }
            
    except Exception as e:
        print(f"Error in API handler: {e}")
        import traceback
        traceback.print_exc()
        return {
            'statusCode': 500,
            'headers': {'Content-Type': 'application/json'},
            'body': json.dumps({
                'error': 'Internal server error',
                'message': str(e)
            })
        }

def handle_health(headers):
    """Health check endpoint"""
    return {
        'statusCode': 200,
        'headers': headers,
        'body': json.dumps({
            'status': 'healthy',
            'message': 'Sentient Wallet Security AI Agent is running',
            'agent_available': agent_available
        })
    }

def handle_test(headers):
    """Test endpoint to verify API is working"""
    return {
        'statusCode': 200,
        'headers': headers,
        'body': json.dumps({
            'message': 'API is working',
            'agent_available': agent_available,
            'timestamp': time.time()
        })
    }

def handle_debug(headers):
    """Debug endpoint to check environment and imports"""
    debug_info = {
        'message': 'Debug information',
        'agent_available': agent_available,
        'python_version': sys.version,
        'project_root': str(project_root),
        'sys_path': sys.path[:3],  # First 3 entries
        'timestamp': time.time()
    }
    
    try:
        # Test imports
        if agent_available:
            debug_info['import_test'] = 'Success'
        else:
            debug_info['import_test'] = 'Failed - using mock data'
    except Exception as e:
        debug_info['import_error'] = str(e)
    
    return {
        'statusCode': 200,
        'headers': headers,
        'body': json.dumps(debug_info)
    }

def handle_scan(body, headers):
    """Handle wallet scanning requests"""
    try:
        address = body.get('address', '')
        
        if not address:
            return {
                'statusCode': 400,
                'headers': headers,
                'body': json.dumps({'error': 'Address is required'})
            }
        
        # Check if already scanning
        if address in scan_status and scan_status[address] == "scanning":
            return {
                'statusCode': 400,
                'headers': headers,
                'body': json.dumps({'error': 'Wallet already being scanned'})
            }
        
        # Start background scan
        scan_status[address] = "scanning"
        scan_results[address] = ""
        
        # Try to use the real agent, fallback to mock data
        try:
            if agent_available:
                agent = WalletSecurityAgent()
                visualizer = WalletVisualizer()
                
                # Get the scan result
                result = agent.scan_wallet(address)
                
                # Get transaction data for visualization
                transactions = agent.get_transactions(address)
                
                # Create interactive dashboard
                dashboard = visualizer.create_interactive_dashboard(transactions, address)
                
                # Store both results
                scan_results[address] = {
                    'security_report': result,
                    'dashboard': dashboard
                }
            else:
                # Use mock data when agent is not available
                mock_result = get_mock_scan_result(address)
                scan_results[address] = {
                    'security_report': mock_result,
                    'dashboard': 'Mock dashboard data'
                }
            
            scan_status[address] = "completed"
            
        except Exception as e:
            print(f"Error during scan: {e}")
            # Fallback to mock data on error
            mock_result = get_mock_scan_result(address)
            scan_results[address] = {
                'security_report': mock_result,
                'dashboard': 'Mock dashboard data'
            }
            scan_status[address] = "completed"
        
        return {
            'statusCode': 200,
            'headers': headers,
            'body': json.dumps({
                'message': 'Scan started',
                'address': address
            })
        }
        
    except Exception as e:
        print(f"Error in handle_scan: {e}")
        return {
            'statusCode': 500,
            'headers': headers,
            'body': json.dumps({'error': f'Scan failed: {str(e)}'})
        }

def handle_status(body, headers):
    """Handle status check requests"""
    try:
        # Extract address from query parameters or body
        address = body.get('address', '')
        
        if not address:
            return {
                'statusCode': 400,
                'headers': headers,
                'body': json.dumps({'error': 'Address is required'})
            }
        
        if address not in scan_status:
            return {
                'statusCode': 404,
                'headers': headers,
                'body': json.dumps({'status': 'not_found'})
            }
        
        status = scan_status[address]
        result = scan_results.get(address, "")
        
        return {
            'statusCode': 200,
            'headers': headers,
            'body': json.dumps({
                'status': status,
                'result': result
            })
        }
        
    except Exception as e:
        return {
            'statusCode': 500,
            'headers': headers,
            'body': json.dumps({'error': f'Status check failed: {str(e)}'})
        }
